apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: front-end
          image: httpd
          copy: website/ /usr/local/apache2/htdocs/
          ports:
            - containerPort: 80
