apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: front-end
          image: httpd 
          ports:
            - containerPort: 80
- name: Copy file with owner and permissions
  copy:
    src: website/
    dest: /usr/local/apache2/htdocs/
